### ISSUE TITLE
Awesome project - having trouble running it

### ISSUE THREAD

**Issue by abvijaykumar** [ismailof/rockberry-player#2]
Hi this is first of all a GREAT project, love it. How can I use it in my Kivy app? when I try to run the test.py I am getting 

Traceback (most recent call last):
   File "test.py", line 15, in <module>
     from rockberry_player.widgets.historyview import format_time_diff
   File "/home/pi/arioAuto/music/rockberry-player/rockberry_player/widgets/historyview.py", line 10, in <module>
     from ..widgets.dialrecycleview import DialRecycleView
   File "/home/pi/arioAuto/music/rockberry-player/rockberry_player/widgets/dialrecycleview.py", line 10, in <module>
     from dialbehavior import DialBehavior
   File "/home/pi/arioAuto/music/rockberry-player/rockberry_player/widgets/dialbehavior.py", line 3, in <module>
     from kivy.input.providers.gpioinput import GPIOEvent, AXIS_COORDS
 ImportError: No module named gpioinput

Can you please help me with some documentation on how I can reuse ur modules

**Comment by ismailof** [comment]
Hi @vijjuk, right now this is more of a personal project and I didn't worry much about making it runnable by general public. In fact, there are some modules related to GPIO that I've modified on kivy code but haven't uploaded yet since is work in progress. That is what's giving you the error.

When I have some time, maybe next week, I will take a look to try to eliminate this errors and give some documentation about how to run it.

Thanks for your interest!

**Comment by abvijaykumar** [comment]
Oh ok cool, thank you..can I reuse your code? or u want to keep it private? I am just building a small music player application for my car

**Comment by ismailof** [comment]
Sure! That is the goal of open source :D

**Comment by abvijaykumar** [comment]
Great..will try to build a widget, and submit it back to u
